language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
      env:
        - SIMULATE_WINFS=false
        - UBUNTU=trusty
        - PYVER=2
    - os: linux
      dist: trusty
      python: 2.7
      env:
        - SIMULATE_WINFS=true
        - UBUNTU=trusty
        - PYVER=2
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - SIMULATE_WINFS=false
        - UBUNTU=trusty
        - PYVER=3
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - SIMULATE_WINFS=true
        - UBUNTU=trusty
        - PYVER=3
    - os: linux
      dist: precise
      python: 2.7
      env:
        - SIMULATE_WINFS=false
        - UBUNTU=precise
        - PYVER=2
    - os: linux
      dist: precise
      python: 2.7
      env:
        - SIMULATE_WINFS=true
        - UBUNTU=precise
        - PYVER=2
    - os: linux
      dist: precise
      python: 3.5
      env:
        - SIMULATE_WINFS=false
        - UBUNTU=precise
        - PYVER=3
    - os: linux
      dist: precise
      python: 3.5
      env:
        - SIMULATE_WINFS=true
        - UBUNTU=precise
        - PYVER=3
#    - os: linux
#      dist: precise
#      python: pypy
#    - os: linux
#      dist: precise
#      python: pypy3
install: "pip install coverage python-coveralls"  # or "coveralls" instead (alternative package)
script: ls -aR && python setup.py build && coverage run tests.py && coverage html && coverage annotate tests.py
after_success:
  - coveralls
