language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
install: "pip install coverage"
script: coverage run tests.py
cache:
  directories:
    - $HOME/.cache/pip
  timeout: 100000
