language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: precise
      python: 2.7
    - os: linux
      dist: precise
      python: 3.5
#    - os: linux
#      dist: precise
#      python: pypy
#    - os: linux
#      dist: precise
#      python: pypy3
install: "pip install coverage python-coveralls"  # or coveralls
script: python setup.py build && coverage run tests.py && coverage html && coverage annotate tests.py
cache:
  directories:
    - $HOME/.cache/pip
  timeout: 300000
after_success:
  - coveralls
